### ISSUE TITLE
Installing RHTAP into an already running OpenShift Cluster

### ISSUE THREAD

**Issue by asshutossh** [redhat-appstudio/tssc-cli#434]
As per  https://docs.redhat.com/en/documentation/red_hat_trusted_application_pipeline/1.3/html/installing_red_hat_trusted_application_pipeline/install#installing_rhtap_with_the_literal_rhtap_cli_deploy_literal_command  OpenShift GitOps and Pipelines Operators  shouldn't be installed already.
Excerpt: 
You must ensure that none of the following operators are already installed in your cluster:
AMQ Streams
Crunch-Data PostgreSQL
OpenShift GitOps
Keycloak
OpenShift Pipelines
Trusted Artifact Signer
Quay
Advanced Cluster Security
Developer Hub

Would editing the config.yaml be a workaround to installing rhtap into an environment with GitOps and Pipelines in place?

```

  openShiftGitOps:
      enabled: &gitopsEnabled false
      namespace: *installerNamespace
    openShiftPipelines:
      enabled: &pipelinesEnabled false
```

**Comment by Roming22** [comment]
Hi,

Disabling the feature themselves will do more than just not installing the subscription, and I would not recommend doing it that way.

We have a fix for this issue in #433, so you have 2 options:
- building the cli from the main branch and setting the `manageSubscription` flag to false.
- editing the `values.yaml.tpl` to hardcode `.subscription.openshift[Pipelines|GitOps].enabled` to `false` and passing the file as  a param with `--values-template`.

**Comment by asshutossh** [comment]
Thanks also I was wondering if you could also provide us with the helm
repository for all the charts installed by rhtap-cli to integrate the
charts directly into our already set up gitops repo for the cluster as this
would allow us to flexibly manage the helm charts. Are these helm charts in
the openshift helm chart repo?

**Comment by Roming22** [comment]
They are in the repo, under `installer/charts`. Note that the installer is taking care of generating the `values.yaml` from `values.yaml.tpl` and orchestrating the deployment of all the charts.

**Comment by asshutossh** [comment]
Thanks, That would mean manually copying out the helm charts individually
into our existing gitops repo ? Or would there be a more elegant way of
maintaining(updating in the future) the helm charts ?

**Comment by Roming22** [comment]
You don't need to copy the charts. You will need to generate the right values.yaml somewhere on your system and pass it to helm (cf https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing)

**Comment by asshutossh** [comment]
Sorry I didn't explain it well about copying the charts. We are deploying the helm charts from a bitbucket repo without access to GitHub from the network where Openshift is running using ArgoCD applications.
For e.g we could reference the helm chart directories as follows (if we had access to GitHub.com )
```

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/asshutossh/rhtap-cli.git # this is the forked repo
    targetRevision: main
    path: installer/charts/rhtap-tas 
```

However, as we don't have network access to Github from the network where OpenShift is installed, we will have to host the helm charts (installer/charts/rhtap-tas) in our own repo to be able to reference it via argocd applications.

**Comment by asshutossh** [comment]
I see all the values needed for installing rhtap-cli deploy --config=tmp/my-config.yaml --debug --dry-run 
This was a long value file (that is why one would use rhtap cli as it takes care of managing the values for all the dependencies) I guess generating the right values.yaml for the helm charts might turn out to be a challenge! 
```
#
# rhtap-tas
#

trustedArtifactSigner:
  enabled: true
  ingressDomain: "<INGRESSDomain>"
  keycloakRealmImport:
    enabled: true
    keycloakCR:
      namespace: rhtap-keycloak
      name: keycloak
  secureSign:
    enabled: true
    namespace: rhtap-tas
    fulcio:
      oidc:
        clientID: trusted-artifact-signer
        issuerURL: https://sso.apps.<IngressDomain>/trusted-artifact-signer
      certificate:
        # TODO: promopt the user for organization email/name input!
        organizationEmail: trusted-artifact-signer@company.dev
        organizationName: RHTAP
  integrationSecret:
    namespace: rhtap 
```
