### ISSUE TITLE
Installation of rhbk-operator is failing with AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces

### ISSUE THREAD

**Issue by asshutossh** [redhat-appstudio/tssc-cli#457]
Invoking the installation with a hardcoded values file to not install openshift-pipelines and openshift-gitops.

`rhtap-cli deploy --values-template installer/charts/values.yaml.tpl --embedded=false`

Currently the operator is being installed with these values:
 
```
 openshiftKeycloak:
    enabled: false
    description: Red Hat Keycloak Operator
    apiResource: keycloaks.k8s.keycloak.org
    namespace: rhbk-operator
    name: rhbk-operator
    channel: stable-v22
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    operatorGroup:
      upgradeStrategy: Default
      **targetNamespaces: []**
```
After the installation following error appears for the operator
```
status:
  cleanup: {}
  conditions:
    - lastTransitionTime: '2025-02-11T09:54:01Z'
      lastUpdateTime: '2025-02-11T09:54:01Z'
      message: 'AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces'
      phase: Failed
      reason: UnsupportedOperatorGroup
  lastTransitionTime: '2025-02-11T09:54:01Z'
  lastUpdateTime: '2025-02-11T09:54:01Z'
  message: 'AllNamespaces InstallModeType not supported, cannot configure to watch all namespaces'
  phase: Failed
  reason: UnsupportedOperatorGroup
```

**Comment by Roming22** [comment]
Can you share the manifest for the subscription please?

**Comment by asshutossh** [comment]
I added the following manually for the operator to get into a successful state.

```
  targetNamespaces:
  - rhtap-keycloak

```
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app.kubernetes.io/instance":"rhtap-subscriptions"},"name":"rhbk-operator","namespace":"rhbk-operator"},"spec":{"targetNamespaces":[],"upgradeStrategy":"Default"}}
    meta.helm.sh/release-name: rhtap-subscriptions
    meta.helm.sh/release-namespace: rhtap
    olm.providedAPIs: Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org
  creationTimestamp: "2025-02-04T10:57:50Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: rhtap-subscriptions
    app.kubernetes.io/managed-by: Helm
  name: rhbk-operator
  namespace: rhbk-operator
  resourceVersion: "751774189"
  uid: 4d4f8014-ec53-4ea0-8ee2-56708ad149e3
spec:
  targetNamespaces:
  - rhtap-keycloak
  upgradeStrategy: Default
```

**Comment by Roming22** [comment]
Does that mean you cleared that hurdle and we can close this issue?

**Comment by asshutossh** [comment]
Well it needs to be fixed in the helm chart so that the operator gets installed successfully.

**Comment by Roming22** [comment]
Can you specify which version you are using?

I can't reproduce on main.
```
16:35:01 - RARNAUD:~/Code/rhtap/cli [main]
> make; ./bin/rhtap-cli template charts/rhtap-subscriptions | grep -A5 "name: rhbk-operator"
# Building './bin/rhtap-cli'
go build -o ./bin/rhtap-cli ./cmd/... 
  name: rhbk-operator
spec:
  targetNamespaces:
  - rhtap-keycloak
  upgradeStrategy: Default
---
--
  name: rhbk-operator
spec:
  name: rhbk-operator
  channel: stable-v24
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---

```

I see you are not using the default `values.yaml.tpl` nor the embedded charts. Could it be that you inadvertently removed something you shouldn't have. The behavior is controlled by those lines in [values.yaml.tpl](https://github.com/redhat-appstudio/rhtap-cli/blob/a46f56f449093b7c2f47a2bb08c4e75164aec2b1/installer/charts/values.yaml.tpl#L72) and [subscriptions.yaml](https://github.com/redhat-appstudio/rhtap-cli/blob/a46f56f449093b7c2f47a2bb08c4e75164aec2b1/installer/charts/rhtap-subscriptions/templates/subscriptions.yaml#L12), and this value in [config.yaml](https://github.com/redhat-appstudio/rhtap-cli/blob/a46f56f449093b7c2f47a2bb08c4e75164aec2b1/installer/config.yaml#L14).

It would be great if you could provide an archive with enough config to reproduce the issue.

**Comment by asshutossh** [comment]
Hello,

I used: origin/release-1.4
Also I used this command to install :
```
 rhtap-cli deploy --values-template installer/charts/values.yaml.tpl
--embedded=false
```
Attached is the values.yaml.tpl, config.yaml and a git diff HEAD output to
see what I might have changed inadvertently.

Regards
Ashutosh

**Comment by Roming22** [comment]
@asshutossh I don't see the files.

**Comment by Roming22** [comment]
@asshutossh Please upload the files. Otherwise I'll close the issue.

**Comment by asshutossh** [comment]
I have been out of Office this week will respond next week. Thank you!

**Comment by asshutossh** [comment]
@Roming22  have uploaded the files. Apologies for the delay:
[valuesyamltpl.zip](https://github.com/user-attachments/files/19532825/valuesyamltpl.zip)

[config.yaml.zip](https://github.com/user-attachments/files/19532836/config.yaml.zip)

**Comment by asshutossh** [comment]
[diff.zip](https://github.com/user-attachments/files/19532857/diff.zip) The git diff HEAD output.

**Comment by asshutossh** [comment]
Couldn't upload all the files as it is. So uploaded as zip!

**Comment by Roming22** [comment]
This bit should set the value properly (and you haven't changed it as far as I can tell):
```
subscriptions:
...
  openshiftKeycloak:
    enabled: {{ $keycloak.Enabled }}
    operatorGroup:
      targetNamespaces:
        - {{ default "empty" $keycloak.Namespace }}
```

I'll look into it and report my findings.
